/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _LIBEGGNOGG_RPC_H_RPCGEN
#define _LIBEGGNOGG_RPC_H_RPCGEN

#include <rpc/rpc.h>

namespace LibEggnogg
{
	#ifdef __cplusplus
	extern "C" {
	#endif


	#define LibEggnogg_RPC 456123789
	#define Stable 3

	#if defined(__STDC__) || defined(__cplusplus)
	#define set_speed 1
	extern  void * set_speed_3(u_long *, CLIENT *);
	extern  void * set_speed_3_svc(u_long *, struct svc_req *);
	#define get_speed 2
	extern  u_long * get_speed_3(void *, CLIENT *);
	extern  u_long * get_speed_3_svc(void *, struct svc_req *);
	#define get_roomdef 4
	extern  char ** get_roomdef_3(void *, CLIENT *);
	extern  char ** get_roomdef_3_svc(void *, struct svc_req *);
	#define get_mapname 5
	extern  char ** get_mapname_3(void *, CLIENT *);
	extern  char ** get_mapname_3_svc(void *, struct svc_req *);
	extern int libeggnogg_rpc_3_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

	#else /* K&R C */
	#define set_speed 1
	extern  void * set_speed_3();
	extern  void * set_speed_3_svc();
	#define get_speed 2
	extern  u_long * get_speed_3();
	extern  u_long * get_speed_3_svc();
	extern int libeggnogg_rpc_3_freeresult ();
	#define get_roomdef 4
	extern  char ** get_roomdef_3();
	extern  char ** get_roomdef_3_svc();
	#define get_mapname 5
	extern  char ** get_mapname_3(void *, CLIENT *);
	extern  char ** get_mapname_3_svc(void *, struct svc_req *);

	#endif /* K&R C */

	extern void init_libeggnogg_rpc_serv();
	extern void exit_libeggnogg_rpc_serv();

	#ifdef __cplusplus
	}
	#endif

	#endif /* !_LIBEGGNOGG_RPC_H_RPCGEN */
}
